### ISSUE TITLE
it can't build the topology yaml file. 

### ISSUE THREAD

**Issue by iproute-net** [arista-netdevops-community/avd-cEOS-Lab#8]
Hi,

I am trying to use the docker-topo to create a topology for arista but it couldn't create the topology file.
I installed docker-topo Without virtualenv, and got no error during the installation
 
root@debian:/lab# docker --version
Docker version 20.10.13, build a224086

root@debian:/lab# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

docker-topo --create base_lab.yml
Traceback (most recent call last):
  File "/usr/local/bin/docker-topo", line 842, in <module>
    main()
  File "/usr/local/bin/docker-topo", line 692, in main
    with open(t_file, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/lab/base_lab.yml'

Best Regards,
Keyvan

**Comment by iproute-net** [comment]
the issue was the file doesn’t exist in the repo
